### PR TITLE
A small optimization concerning Streams

### PR DESCRIPTION
**Pull request by MSDarwish2000**
I've just made the library use java's built-in streams or if not available, similarly-named ones and made naming convention more Java-like.
The goal is to make it easier to use 

For example, instead of having to use this
```java
InStream stream = new FileInStream("archive.7z");
InArchive archive = InArchive.open(stream);
```
or this
```java
archive.extractEntry(i, new IoSequentialOutStream(new FileOutputStream(path)));
```

You can use this
```java
RandomAccessFile file = new RandomAccessFile("archive.7z", "r");
InputArchive archive = InputArchive.open(file);
```
or this
```java
archive.extractEntry(i, new FileOutputStream(path));
```

### CODE REVIEW

**Comment by seven332** [comment]
I admit it's a bad idea to design the Java APIs based on the 7z c++ APIs. It's better to use existing `InputStream` rather than create `SequentialInStream` and `InStream`.

Please focus on the change. If you want to fix/improve other parts, please create a new branch. It's hard to review multiple thousands lines of changes.

Please keep the code style. Especially, block indentation and import statements.

**Comment by MSDarwish2000** [comment]
Thanks for your advice. Maybe I'm misusing Pull requests as I'm new to Git & GitHub. As you can see I'm making my edits to a fork, so do you mean to keep my fork separate?
As for Code styling I'm using Android Studio's default Indentation & formatting which indent blocks by 4 spaces, which is also oracle's & google's conventions. So for consistency I've reformatted all files to use 4-spaces.

The bad part is that I have no experience in Android Native Code or C++, so I can't continue developing serious parts of the project. But, I've used your library in the past and it was the best option, so I hope you continue developing it if you can.

Thanks again for your advice and I wish you happy time

**Comment by seven332** [comment]
Pull requests are welcome. Please read the GitHub help article [About pull requests](https://help.github.com/en/articles/about-pull-requests).

> Pull requests let you tell others about changes you've pushed to a branch in a repository on GitHub.

All changes you've pushed to the master branch are presented to me. Some changes are not related to the topic `A small optimization concerning Streams`. Typically, a new branch is created to hold only the changes related to the topic.

**Comment by borisbrodski** [comment]
Hello,

sorry for entering the discussion on a closed pull request. But I would like to add, that ...

Using Java stream classes is kind of misleading here. The Java stream API is simply not a good match for 7-zip.

You can't open an archive if InputStream is passed (because of the missing seek operation). You can restrict extract method to accept (for example) only FileInputStream, but this prevents other possible usages, like extracting archives while downloading it. (Used by JDownloader)

Also a API similar to the convenient Java zip API (like just reading items from the InputStream) is not possible, since 7-zip engine pushes extracted data to the writer doing it potentially from an other thread.

Designing API for 7-Zip-JBinding I had to choose

* Make API more Java like, simple and error resistant, but cut some (most cool) features or
* Follow less attractive and intuitive C++ API, but provide full access to all the features of the 7-zip engine

I choosed the second one, at least as a starting point. I planned to build a simplified API above C++ API, but didn't find yet the way, that would justify the afford. If you would come up with a such API, that is built on top of the existing 7-Zip-JBinding API, this would be great.

Cheers,
Boris Brodski

PS
I'm the maintainer of the original 7-Zip-JBinding project, not this cool fork :)

**Comment by MSDarwish2000** [comment]
Hello,

Of course, your participation is welcome and thank you for sharing your knowledge and experience.

The pull request was mainly about replacing the Sequential streams with Java streams interfaces which does the as I think. And implementing new functions and constructors which accepts java's seekable solution for files RandomAccessFile, while keeping the current seekable streams interface with just a rename for more java-friendly name.

I've closed the pull request recently as I opened it when I had almost no knowledge about forks and pull requests ruining the whole pull request and also after I found @seven332 had implemented it himself.  I truly apologize for him for abandoning the pull request and not replying to his comment. And thank you both for sharing your work with community ❤

Best wishes,
Mohamed Darwish

**Pull request closed without merging**
